steps:
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/nifty-garden-411010/api/mennr-tech-api-image:tag1', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west2-docker.pkg.dev/nifty-garden-411010/api/mennr-tech-api-image:tag1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'mennr-tech-api-image', '--image', 'us-west2-docker.pkg.dev/nifty-garden-411010/api/mennr-tech-api-image:tag1', '--region', 'us-west2']

options:
  logging: NONE

images:
- 'us-west2-docker.pkg.dev/nifty-garden-411010/api/mennr-tech-api-image:tag1'
